### ISSUE TITLE
Unknown playerAnimType

### ISSUE THREAD

**Issue by volkv** [T-Maxxx/rotu-custom#1]
Привет! Спасибо, что делишься своими наработками.
У меня при запуске сервера ошибка вылетает:
**Server fatal crashed: Unknown playerAnimType "bot_dog_attack" in "defaultweapon_mp"**
ЧЯДНТ?

**Comment by T-Maxxx** [comment]
Увы, репозиторий залился не полностью. У меня мод компилируется из отдельной папки, не связанной с игрой. Тут же не хватает линкера и, может быть, еще чего-то.
https://github.com/T-Maxxx/rotu-custom/blob/master/mod/raw/mp/playeranimtypes.txt#L25
https://github.com/T-Maxxx/rotu-custom/blob/master/mod/raw/weapons/rotu_mp/defaultweapon_mp#L1
https://github.com/T-Maxxx/rotu-custom/blob/master/mod/raw/mp/playeranim.script#L137
Анимация присутствует, она есть в конфиге оружия и она добавлена в игру, так что она не может не работать. Подозреваю, что проблема где-то твоей папке с ModTools'ами, например, намешаны разные моды.
Я более детально разберусь с содержимым репозитория, когда будет время. Это было немного больно отгружать 140 мб со скоростью 400 кб\с.

**Comment by T-Maxxx** [comment]
@volkv Попробуй скомпилировать сейчас, из отдельной папки.

**Comment by volkv** [comment]
@T-Maxxx я не использовал ModTools :) Просто запустил !makeMod.bat и Deploy )))
Подозреваю, что проблема именно в этом ) Сорри, я только начал погружаться во все это. Вот на этом этапе у меня ничего не выходит -     
**linker_pc.exe -language english -compress mod**
ModTools скачал, сейчас буду разбираться :)

**Comment by volkv** [comment]
Все, запустил :) Буду тестить. Спасибо.
